const accountActionTypes = {
  ACCOUNT_SET_AUTHENTICATED_USER: 'ACCOUNT/SET_AUTHENTICATED_USER',
  ACCOUNT_DELETE_AUTHENTICATED_USER: 'ACCOUNT/DELETE_AUTHENTICATED_USER',
  ACCOUNT_SET_USER_ATTRIBUTES: 'ACCOUNT/SET_USER_ATTRIBUTES',
  ACCOUNT_SET_PROFILE: 'ACCOUNT/SET_PROFILE',
  ACCOUNT_GET_PROFILE: 'ACCOUNT/GET_PROFILE',
  ACCOUNT_ADD_LANE: 'ACCOUNT/ADD_LANE',
  ACCOUNT_DELETE_LANE: 'ACCOUNT/DELETE_LANE',
  SET_PROFILE_PIC: 'ACCOUNT/SET_PROFILE_PIC',
  SET_LOGO: 'ACCOUNT/SET_LOGO',
  ACCOUNT_SET_USER_SESSION: 'ACCOUNT/SET_USER_SESSION',
  ACCOUNT_SIGN_OUT_AUTHENTICATED_USER: 'ACCOUNT/SIGN_OUT_AUTHENTICATED_USER',
  ACCOUNT_SET_AUTHENTICATION_INPROGRESS:
    'ACCOUNT/SET_AUTHENTICATION_INPROGRESS',
  ACCOUNT_SET_USER_DATA: 'ACCOUNT/SET_USER_DATA',
};

export const patronActionTypes = {
  GET_PATRON_SETTING: 'PATRON/GET_PATRON_SETTING',
};

export const merchantActionTypes = {
  GET_MERCHANT_INFO: 'MERCHANT/GET_MERCHANT_INFO',
  SET_REWARDS: 'REWARDS/SET_REWARDS',
};

export const commonActionTypes = {
  API_FETCH_INPROGRESS: 'COMMON/API_FETCH_INPROGRESS',
};

export const statisticsActionTypes = {
  GET_STATISTICS_INFO: 'STATISTICS/GET_STATISTICS',
};

export const programActionTypes = {
  GET_PROGRAM_INFO: 'PROGRAM/GET_PROGRAM',
};

export const rulesActionTypes = {
  GET_RULES_INFO: 'RULES/GET_RULES',
  PATCH_RULES_INFO: 'RULES/PATCH_RULES',
};

export default accountActionTypes;
