import userGroupsTypes from './users';

const ROUTES = {
  HOME: '/',
  ACCOUNT: '/account',
  ACTIONS: '/actions',
  CONVERSATION_DETAIL: '/conversations/:id',
  CONVERSATIONS: '/conversations',
  COUPON_BOOK: '/couponbook',
  LOCATION_DETAIL: '/locations/:id',
  LOCATIONS: '/locations',
  MERCHANT: '/m',
  MERCHANT_DETAILS: '/merchants/:id',
  MERCHANTS: '/merchants',
  NEWS_DETAILS: '/news/:id',
  NEWS: '/news',
  NOT_FOUND: '/not-found',
  PATRON: '/p',
  PATRON_INFO: '/patrons/:id',
  PATRONS: '/patrons',
  PROGRAM: '/program',
  PROFILE: '/profile',
  QR: '/qr',
  REWARD_DETAIL: '/rewards/:id',
  REWARDS: '/rewards',
  RULES: '/rules',
  SEARCH: '/search',
  STATISTICS: '/statistics',
  SUGGESTION_DETAIL: '/suggestions/:id',
  SUGGESTIONS: '/suggestions',
  SURVEY_DETAIL: '/surveys/:id',
  SURVEY_ADD: '/surveys/add',
  SURVEYS: '/surveys',

  CONFIRM: '/confirm',
  EMAIL: '/email',
  JOIN: '/join',
  PASSWORD: '/password',
  PRIVACY: '/privacy',
  SIGN_IN: '/signin',
  TERMS: '/terms',
  ACKNOWLEDGEMENTS: '/acknowledgements',
};

export const ROUTE_ACCESS = {
  ACCOUNT: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  ACTIONS: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  CONVERSATION_DETAIL: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  CONVERSATIONS: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  COUPON_BOOK: [userGroupsTypes.PATRON],
  LOCATION_DETAIL: [userGroupsTypes.MERCHANT],
  LOCATIONS: [userGroupsTypes.MERCHANT],
  MERCHANT: [userGroupsTypes.MERCHANT, userGroupsTypes.CASHIER],
  MERCHANT_DETAILS: [userGroupsTypes.PATRON],
  MERCHANTS: [userGroupsTypes.PATRON],
  NEWS_DETAILS: [
    userGroupsTypes.PATRON,
    userGroupsTypes.MERCHANT,
    userGroupsTypes.CASHIER,
  ],
  NEWS: [
    userGroupsTypes.PATRON,
    userGroupsTypes.MERCHANT,
    userGroupsTypes.CASHIER,
  ],
  NOT_FOUND: [
    userGroupsTypes.PATRON,
    userGroupsTypes.MERCHANT,
    userGroupsTypes.CASHIER,
  ],
  PATRON: [userGroupsTypes.PATRON],
  PATRON_INFO: [userGroupsTypes.CASHIER, userGroupsTypes.MERCHANT],
  PATRONS: [userGroupsTypes.CASHIER, userGroupsTypes.MERCHANT],
  PROGRAM: [userGroupsTypes.MERCHANT],
  PROFILE: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  QR: [
    userGroupsTypes.CASHIER,
    userGroupsTypes.MERCHANT,
    userGroupsTypes.PATRON,
  ],
  REWARD_DETAIL: [userGroupsTypes.MERCHANT],
  REWARDS: [userGroupsTypes.MERCHANT],
  RULES: [userGroupsTypes.MERCHANT],
  SEARCH: [userGroupsTypes.PATRON],
  STATISTICS: [userGroupsTypes.MERCHANT],
  SUGGESTION_DETAIL: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  SUGGESTIONS: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  SURVEY_DETAIL: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
  SURVEY_ADD: [userGroupsTypes.MERCHANT],
  SURVEYS: [userGroupsTypes.PATRON, userGroupsTypes.MERCHANT],
};

export default ROUTES;
